### ISSUE TITLE
Incorrectly generated mutation field input type

### ISSUE THREAD

**Issue by martasd** [tOgg1/graphene-django-cud#1]
I have a model called `Beo` with a many-to-many field called `labels`  like this:

```
class Beo(BaseModel):
    ...
    labels = ManyToManyField(BeoLabel, blank=True)
```

I also have a create mutation for labels with the default input type:

![image](https://user-images.githubusercontent.com/591911/65495807-9b749100-deb7-11e9-97c5-40b787904380.png)

In the create mutation, I would like to specify that it is possible to create labels directly while creating the Beo instance:

```
class CreateBeo(DjangoCreateMutation):
    class Meta:
        model = Beo
        many_to_many_extras = {
           "labels": {"exact": {"type": "CreateBeoLabelInput"}},
```

In the resulting mutation, however, I only see the `[ID] ` as the input type for labels while expecting something like `[CreateBeoLabelInput]`:

<img width="142" alt="Screen Shot 2019-09-18 at 16 23 16" src="https://user-images.githubusercontent.com/591911/65495883-bba45000-deb7-11e9-8801-3bfd61a86d1f.png">

**Comment by martasd** [comment]
I have also tried:

`"labels": {"add": {"type": "CreateBeoLabelInput"}},`

but it did not make any difference- the input type remains `[ID]`.

**Comment by tOgg1** [comment]
Hi Martin.

It seems I am able to reproduce the error. I will get back to you during the course of the day.

Just to make sure: Have you added nodes for both Beo and BeoLabel? And a CreatebeoLabel-mutation?

**Comment by tOgg1** [comment]
The issue was due to a typo in the method which converts ManyToMany fields into its graphene-counterpart. Bumping the version to 0.0.15 should fix the issue.

**Comment by martasd** [comment]
Excellent. I will give it a try.

And yes, I do have both nodes and the mutation as well.

**Comment by martasd** [comment]
Yes, this indeed fixes the issue. 👍
