### ISSUE TITLE
This package ROCKS!!!

### ISSUE THREAD

**Issue by jyoost** [tOgg1/graphene-django-cud#101]
I am at the beginning of a big django graphene project.  I got to the mutations yesterday and got stuck on how to implement without writing a bunch of redundant code.

Then I found graphene-django-cud. WOW! this will save me about 40 hours of coding.

THANK YOU VERY MUCH 

If I can submit a PR in the future I would be proud to be a part of this Project.

**Comment by tOgg1** [comment]
Thanks! :) 

You are very welcome to contribute!
