### ISSUE TITLE
Feature request: (batch) delete by IDs

### ISSUE THREAD

**Issue by fkromer** [tOgg1/graphene-django-cud#11]
I think it would be very valuable to being able to delete several model instances via one GraphQL mutation call by IDs (or potential other unique fields).

One possible design could combine the fields of [DjangoDeleteMutation](https://graphene-django-cud.readthedocs.io/en/latest/guide/mutations.html#djangodeletemutation) and [DjangoBatchDeleteMutation](https://graphene-django-cud.readthedocs.io/en/latest/guide/mutations.html#djangobatchdeletemutation) to something like this in case all IDs have been found

```yaml
mutation {
  deleteModels(id: [1, 2, 3]) {
    deletionCount
    deletedIds
    missedIds
  }
}

{
  "data": {
    "deleteModels": {
      "deletionCount": 3,
      "deletedIds": [1, 2, 3],
      "missedIds": null,
    }
  }
}
```

and this in case some Id(s) have not been found

```yaml
mutation {
  deleteModels(id: [1, 2, 3, 4, 5]) {
    deletionCount
    deletedIds
    missedIds
  }
}

{
  "data": {
    "deleteModels": {
      "deletionCount": 3,
      "deletedIds": [1, 2, 3],
      "missedIds": [4, 5],
    }
  }
}
```

What do you think?

**Comment by tOgg1** [comment]
Yep, this is a good proposal. I will write it in my backlog. As per now, if you need this functionality urgently, you can get the same by creating an appropriate `id__in`-filter for DjangoBatchDeleteMutation.

In terms of API-design, this will most likely result in DjangoBatchDeleteMutation being split into two versions, one with a list of IDs, and one with filtering.

**Comment by tOgg1** [comment]
This is now live in v0.6.0-rc.0. Will do some quick testing before releasing the full version.

**Comment by fkromer** [comment]
@tOgg1 Thx a lot!
