### ISSUE TITLE
Release after graphene-django's compat.JSONField removal

### ISSUE THREAD

**Issue by Natureshadow** [tOgg1/graphene-django-cud#113]
As this proejct has already noticed and udpated accordingly, `compat.JSONField` was removed from graphene-django.

Unfortunately, they [did that change in a patch release](https://github.com/graphql-python/graphene-django/issues/1428) ☹.

Still, if possible, please make a timely release to PyPI so that, no matter whether graphene-django will fix the versioning issue on their side, we can continue using graphene-django-cud.

**Comment by tOgg1** [comment]
Thanks for the report!

Closed with version 0.11.0.
