### ISSUE TITLE
Fix pytest warnings

### ISSUE THREAD

**Issue by fkromer** [tOgg1/graphene-django-cud#12]
When I run tests in `django` projects with `pytest` and `pytest-django` I get some warnings from which at least one is caused by `graphene-django-cud`.

```python
.../graphene_django_cud/converter.py:57: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
    name = to_const(force_text(name))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============================ SnapshotTest summary ============================
```

It's not critical cause it's about warnings but a bit annoying cause potential own warnings are kind of hidden. Depending on which `django` versions you want to support there needs to be taken some care w.r.t. backward compatibility when fixing the warnings.

**Comment by tOgg1** [comment]
Thanks, I will look into this.

I intend on supporting Django 2.0 for a while, but python2 and Django 1.x support is not intended.

However, it does seem like `force_str` exists in Django 1.11. So simply making the change here should be unproblematic.

**Comment by fkromer** [comment]
The warnings popped up in Django 3. I don't care about Django 1 but probably others do. Seems like Django 1 reaches end of life end of April 2020 https://www.djangoproject.com/weblog/2015/jun/25/roadmap/ .

**Comment by tOgg1** [comment]
It does indeed. I think some (or many) of those still using Django 1 also require python2 support, which I am very deliberately against supporting for graphene-django-cud.

**Comment by fkromer** [comment]
I totally agree. There are reasons why versions reach end of life.
