### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by sukhjindersukh** [tOgg1/graphene-django-cud#19]
When I tried to create a mutation using DjangoCreateMutation

I am getting 
NameError: name 'DjangoCreateMutation' is not defined

Plz help me how to resolve this

**Comment by tOgg1** [comment]
Have you imported DjangoCreateMutation? If so: where from?

**Comment by sukhjindersukh** [comment]
Please mention in user guide all the imports as well, it would be very helpful for beginners like me.

**Comment by tOgg1** [comment]
The correct import for DjangoCreateMutation should be 

`from graphene_django_cud.mutations import DjangoCreateMutation`.

I will add a task for improving the documentation in general. Will add that as a specific task. Thanks for reporting!
