### ISSUE TITLE
Problem in the disambiguate_id function

### ISSUE THREAD

**Issue by adavoudi** [tOgg1/graphene-django-cud#22]
Hi,
I have a model with a foreign key named `kpi` which allude to another model with a PK named `key` (with type string). The problem is that whenever I try to insert into the first model with a create mutation and `kpi="somekey"`, I get an error regarding that `kpi_id=-1` does not exist. 

I figured out that it is because of what the `disambiguate_id` does to the provided id:

```python
def disambiguate_id(ambiguous_id: Union[int, float, str]):
    """
    disambiguate_id takes an id which may either be an integer-parsable
    variable, either as a string or a number; or it might be a base64 encoded
    global relay value.

    The method then attempts to extract from this token the actual id.

    :return:
    """
    # First see if it is an integer, if so
    # it is definitely not a relay global id
    final_id = -1
    try:
        final_id = int(ambiguous_id)
        return final_id
    except ValueError:
        # Try global value
        (_, final_id) = from_global_id(ambiguous_id)
    finally:
        return final_id
``` 

this function assumes that if a provided id is not integer-parsable, it is a relay id. However, at least in my case, this is not true. In this case, this function returns `-1` which is wrong (I expect it to return my original id, i.e. `somekey`).

The problem also exist in the `disambiguate_ids` function.

**Comment by tOgg1** [comment]
Hello,

Yep, this is a problem I have been anticipating. I will fix it at my earliest convenience. Thanks for reporting!
