### ISSUE TITLE
Validation error on unique_together fields outputs empty message.

### ISSUE THREAD

**Issue by geekashu** [tOgg1/graphene-django-cud#30]
```
class Dashboard(models.Model):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dashboards')

    class Meta:
        ordering = ['-id']
        unique_together = ['name', 'owner']
```

The validation error gets hit properly, but the message field is empty for this error.
`{"errors":[{"message":"","locations":[{"line":2,"column":21}],"path":["createDashboard"]}],"data":{"createDashboard":null}}`

**Comment by tOgg1** [comment]
It's not clear to me that this is related to this library, but I'll do a quick investigation.

**Comment by tOgg1** [comment]
I am unable to reproduce this.

**Comment by tOgg1** [comment]
Closing until further information is provided.
