### ISSUE TITLE
Error updating nested field using many_to_one_extras when there are restrictions on related model

### ISSUE THREAD

**Issue by FloderCC** [tOgg1/graphene-django-cud#33]
Above all, many congratulations for such a good job.
Suppose there are two models, a model A and a model B that has a foreign key to model A with and related name = "ab," and also two fields "name" and "value".

So to update a model A and setting as many models B as necessary I specify in UpdateAMutation:
many_to_one_extras = {
             "ab": {
                 "exact": {"type": "auto"}
             },

In model B I have the unique type constraint (unique_together = ('name', 'a_id'))

The problem is that when I try to update A and its relations in B in the same mutation, if there is some value in B that already existed with equal ('name', 'a_id'), the constraint throws error.

Please is there a way to do it?

**Comment by FloderCC** [comment]
I understand that checking by the object id in the upsert_obj method in core.py the related object will never appear, since in this case the related object id is never added and therefore disambiguate_id (input.get ("id")) It will always return null and the object will end up being created. So I think that they could use unique type constraints in related models (I don't know how to do it) to get the id and do an update instead of creating and deleting

**Comment by tOgg1** [comment]
Hi,

Sorry about the delayed response.

I am having some trouble wrapping my head around exactly what your issue is (and how it relates to this project). Could I ask you to give me an example?

**Comment by tOgg1** [comment]
Closing until further information is provided.
