### ISSUE TITLE
Redundant type created for choice charfield

### ISSUE THREAD

**Issue by bigtimecriminal** [tOgg1/graphene-django-cud#35]
When creating a simple model with a choice charfield: 

```
# Model

BAR_CHOICES = [
    ('OPTION1', 'Option 1'),
    ('OPTION2', 'Option 2'),
    ('OPTION3', 'Option 3')
]


class Foo(models.Model):
    bar = models.CharField(max_length=32, choices=BAR_CHOICES, null=True, blank=True)

# Type

from graphene_django import DjangoObjectType as DOT

class FooType(DOT):
    class Meta:
        model = Foo
        filter_fields: Dict[str, str] = {}

# Mutation

class CreateFoo(DjangoCreateMutation):
    class Meta:
        model = Foo
```

This results in two identical enum types being generated with different names, `FooBar` and `FooBarInput`. Is this intended behavior, or a valid issue?

**Comment by tOgg1** [comment]
Hi!

This is not intentional behaviour, and should not happen. Although I know we've had some issues with this before. Could you please send me which graphene, graphene-django and graphene-django cud versions you have installed?

**Comment by bigtimecriminal** [comment]
I see! Good to know it is not intentional. My versions are:
```
graphene-django==2.13.0
graphene-django-cud==0.6.5
```

**Comment by bigtimecriminal** [comment]
I was taking a look at this issue today, and it looks like it might be intentional. `Input` is appended to choice field types in two places:

https://github.com/tOgg1/graphene-django-cud/blob/develop/graphene_django_cud/converter.py#L108

and here:

https://github.com/tOgg1/graphene-django-cud/blob/develop/graphene_django_cud/converter.py#L80

Tests will not run with it removed.
