### ISSUE TITLE
Autogenerated graphene INPUT fields interpret Decimal fields as Float fields

### ISSUE THREAD

**Issue by ghost** [tOgg1/graphene-django-cud#56]
Bug: The ObjectTypeInput, auto generated by a create/update/patch mutation interprets Django Decimal fields as Float fields. Graphene has added support for Decimal fields.

I am required to write my mutation this way:
```
mutation updateMultipleFieldsProjectl($projectId: ID!, $name: String, $degradation:
        Float = 10.00) {
            updateProject(id: $projectId, input: {name: $name , degradation: $degradation})
```

However, in my model, degradation is a django DecimalField.  
Currently I am required to hook into `before_save` and convert the Float to a Decimal, and define it as a Float in my graphql query.

**Comment by tOgg1** [comment]
This should be solved by #53, and is now released with v0.8.0. Please see if upgrading fixes your issue.
