### ISSUE TITLE
Is "id" required for update?

### ISSUE THREAD

**Issue by markddavidoff** [tOgg1/graphene-django-cud#57]
the examples in the guide do:

```
mutation {
    patchUser(input: {name: "John Doe"}){
        user{
            id
            name
            address
        }
    }
}
```
 but when i do a similar query in my code, with only an input passed i get:
 ` argument \"id\" of type \"ID!\" is required but not provided.`

**Comment by tOgg1** [comment]
That is correct, this is an issue with the documentation. The correct usage should be, e.g.:

```
mutation {
    patchUser(id: "VXNlck5vZGU6MQ==", input: {name: "John Doe"}){
        user{
            id
            name
            address
        }
    }
}
```

**Comment by markddavidoff** [comment]
thanks for the clarification, i thought i was going crazy there 😅

**Comment by markddavidoff** [comment]
https://github.com/tOgg1/graphene-django-cud/pull/58
