### ISSUE TITLE
History does not get tracked for many to many field

### ISSUE THREAD

**Issue by martasd** [tOgg1/graphene-django-cud#6]
Hi Tormod,

I have the following model and mutation defined:

```
class Beo(BaseModel):
    ... (some simple fields are here)
    organizers = ManyToManyField(
        UserProfile, related_name="organized_beos", blank=True,
        through="BeoOrganizer", through_fields=("beo", "organizer")
    )
    history = HistoricalRecords(user_model=UserProfile)

class BeoOrganizer(BaseModel):
    beo = ForeignKey(Beo, on_delete=CASCADE)
    organizer = ForeignKey(UserProfile, related_name="organized_beo", on_delete=CASCADE)
    history = HistoricalRecords(user_model=UserProfile)

class CreateBeo(DjangoCreateMutation):
    class Meta:
        model = Beo
        many_to_many_extras = = {
               "organizers": {"exact": {"type": "ID"}},
}
```

Beo is a model which uses `django-simple-history`, a library to keep track of object changes. According to the docs:

"django-simple-history functions by saving history using a post_save signal every time that an object with history is saved."

When I execute the `CreateBeo` mutation, the history gets properly recorded for simple fields of the new beo object as expected. However, it does not get recorded for the many-to-many `organizers` field even though there is a new entry in the `BeoOrganizers` table. I assume this is related to history using the `post_save` signal. Is that right? Is this something that could be enabled or is that an inherent limitation? 

Many thanks!

**Comment by tOgg1** [comment]
Hi Martin,

I will do some investigation. Can you confirm that this in fact a problem with `graphene-django-cud` and not with `django-simple-history`? E.g. if you perform the same tasks manually (create object, add to m2m-relation), do you get the behaviour you epxect?

If you are attaching existing objects to the m2m-relation, the `post_save`-signal will not be fired; the `m2m_changed` will be fired (https://docs.djangoproject.com/en/2.2/ref/signals/#m2m-changed). I don't know if that is a limitation with `django-simple-history`.

All saving of instances done in `graphene_django_cud` is performed using the regular `.save()` method. Hence `post_save` _should_ be fired in all relevant scenarios.

**Comment by tOgg1** [comment]
Actually, reading your comment a bit more carefully, it should probably fire the `post_save` signal there. I'll get back to you.

**Comment by martasd** [comment]
Sorry, Tormod, I was mistaken. This is an issue with `django-simple-history` which fails to create a historical record even when using the shell, so it's not an issue in this library.
