### ISSUE TITLE
Custom PK incompatibility

### ISSUE THREAD

**Issue by Bernat417** [tOgg1/graphene-django-cud#66]
Hello there!
I've been trying to use graphene-django-cud with models where 'id' is not the name of the pk and it crashes. I don't see a way to set that value and 'id__in' seems to be 'hardcoded' in several places. Is there a way of setting custom pks I'm missing?

**Comment by tOgg1** [comment]
Hi @Bernat417.

There are likely to be some locations where this is an issue, yes. There are some places where `id` is currently used in place of `pk`.

Could you detail your use-case quickly, as a basis for me to create a failing test, perhaps? And then I'll get right on fixing this.
