### ISSUE TITLE
Alias `only_fields` as `fields` and `exclude_fields` as `exclude`

### ISSUE THREAD

**Issue by cpmsmith** [tOgg1/graphene-django-cud#73]
TL;DR, Graphene-Django is renaming them, and I assume `graphene-django-cud` wants to match it: graphql-python/graphene-django#691 

To match Django REST Framework's `ModelSerializer`, Graphene-Django is switching the names of `only_fields` and `exclude_fields` to `fields` and `exclude` respectively. They've added the new names as aliases already, and [are now raising DeprecationWarnings](https://github.com/graphql-python/graphene-django/pull/980) when using the old names, as they plan to remove the old names in v3. I expect that `graphene-django-cud` want to follow their lead on this?

**Comment by tOgg1** [comment]
Yep, absolutely. Thanks for the heads up. Will fast track this.
